name: Vmess Daily API Trigger

on:
  schedule:
    - cron: '0 2 * * *'   # 09:00 WIB
    - cron: '0 11 * * *'  # 18:00 WIB
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Action (freeze or unfreeze)
        run: |
          HOUR=$(date -u +"%H")
          echo "Current UTC hour: $HOUR"
          if [ "$HOUR" -eq "2" ]; then
            echo "ACTION=unfreeze" >> $GITHUB_ENV
          elif [ "$HOUR" -eq "11" ]; then
            echo "ACTION=freeze" >> $GITHUB_ENV
          else
            echo "Invalid schedule time: $HOUR"
            exit 1
          fi

      - name: Call Vmess API
        run: |
          if [ "$ACTION" == "unfreeze" ]; then
            URL="https://sahabatssh.com/service/vmess_hourly/unfreeze?get_id=2936"
          else
            URL="https://sahabatssh.com/service/vmess_hourly/freeze?get_id=2936"
          fi

          echo "Calling URL: $URL"
          curl -X POST "$URL" \
            -H "Cookie: ${{ secrets.USER_COOKIE }}" \
            -H "User-Agent: Mozilla/5.0" \
            -H "Accept: */*" \
            -L -v --max-time 20
